// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlK3ITIcqLilgBxEpA_61CV7xooOFqhtg',
    appId: '1:99032348724:web:7855a58ac731b10543b261',
    messagingSenderId: '99032348724',
    projectId: 'ai-meal-planner-b8181',
    authDomain: 'ai-meal-planner-b8181.firebaseapp.com',
    storageBucket: 'ai-meal-planner-b8181.firebasestorage.app',
    measurementId: 'G-L4215GYQLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3ujlr1Ws1IWFdxwHCpYLyFk7ZjeyTfw',
    appId: '1:99032348724:android:990641664dcd31ec43b261',
    messagingSenderId: '99032348724',
    projectId: 'ai-meal-planner-b8181',
    storageBucket: 'ai-meal-planner-b8181.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlK3ITIcqLilgBxEpA_61CV7xooOFqhtg',
    appId: '1:99032348724:web:82aeb5c768458e9043b261',
    messagingSenderId: '99032348724',
    projectId: 'ai-meal-planner-b8181',
    authDomain: 'ai-meal-planner-b8181.firebaseapp.com',
    storageBucket: 'ai-meal-planner-b8181.firebasestorage.app',
    measurementId: 'G-QEWTK39QBB',
  );
}
